import Providers from './styles/MainStyledComp';
import GlobalStyles from './styles/GlobalStyles';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavbarComponent from './globalcomponents/NavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

<html lang="en">
<body>
  <Providers>
    <GlobalStyles />
    <NavbarComponent />
    {children}
  </Providers>
</body>
</html>
  )
}














